// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ4fWnVT430gvnKxZCdaYwN4g309FlJ8M',
    appId: '1:401389043758:web:bdcb1d54dbfc5f8d9f9fbf',
    messagingSenderId: '401389043758',
    projectId: 'innstantbook',
    authDomain: 'innstantbook.firebaseapp.com',
    storageBucket: 'innstantbook.appspot.com',
    measurementId: 'G-8DDDQ8JCPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbvAwufBI4WYqAGEPWh6YcmxHX2_UCFgg',
    appId: '1:401389043758:android:5e23d0366d5ccde39f9fbf',
    messagingSenderId: '401389043758',
    projectId: 'innstantbook',
    storageBucket: 'innstantbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVUP7YVxzIRuXa_UwBbVQDcFuHpvNC6tI',
    appId: '1:401389043758:ios:7ecbd43f056b28bf9f9fbf',
    messagingSenderId: '401389043758',
    projectId: 'innstantbook',
    storageBucket: 'innstantbook.appspot.com',
    iosBundleId: 'com.example.innstantbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVUP7YVxzIRuXa_UwBbVQDcFuHpvNC6tI',
    appId: '1:401389043758:ios:5f946050323ed94c9f9fbf',
    messagingSenderId: '401389043758',
    projectId: 'innstantbook',
    storageBucket: 'innstantbook.appspot.com',
    iosBundleId: 'com.example.innstantbook.RunnerTests',
  );
}
